"""
VOLTERRA — Digital Twin Simulation Engine
==========================================
Implements the VOLTERRA Digital Twin Design Document (Version 1.0, September 2026).

Answers the central simulation question:
    "If I choose this action, what happens?"

Core capabilities:
1. Sits at the SIMULATE stage of the closed-loop pipeline.
2. Parallel branching: simulates each candidate independently from the baseline.
3. Physical asset fidelity:
   - Battery charge/discharge rates, state-of-charge limits, degradation impact of use.
   - Load-shifting effects: reshaping the demand curve over the decision horizon.
   - Renewable supply dynamics over time.
   - Constraint boundaries: minimum battery reserve, maximum allowable peak demand.
4. Common action interface: shared contract for virtual and physical execution.
5. Baseline calculation for the post-action Measure stage.
"""

from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Dict, Any, List, Optional, Tuple, Union

from prediction_engine import SystemState


@dataclass
class TwinConfig:
    """Configuration for initializing a Digital Twin instance."""
    initial_state: SystemState
    max_discharge_kw: float = 5.0
    max_charge_kw: float = 5.0
    efficiency: float = 0.95
    capacity_kwh: float = 13.5
    cost_per_kwh: float = 0.50
    # Constraint boundaries (Section 5)
    min_battery_reserve_pct: float = 20.0
    max_allowable_peak_kw: float = 15.0
    # Degradation modeling parameters
    battery_cycle_life: int = 4000


@dataclass
class SimulationMetrics:
    """Key simulated metrics generated by the Digital Twin (Section 4.2)."""
    peak_demand_kw: float
    cost: float
    battery_reserve_pct: float
    renewable_utilization_pct: float
    discharged_kw: float = 0.0
    shifted_kw: float = 0.0
    # Battery degradation impact of use (Section 5)
    degradation_impact_pct: float = 0.0
    # Constraint compliance check (Section 5)
    is_feasible: bool = True
    constraint_notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "peak_demand_kw": self.peak_demand_kw,
            "cost": self.cost,
            "battery_reserve_pct": self.battery_reserve_pct,
            "renewable_utilization_pct": self.renewable_utilization_pct,
            "discharged_kw": self.discharged_kw,
            "shifted_kw": self.shifted_kw,
            "degradation_impact_pct": self.degradation_impact_pct,
            "is_feasible": self.is_feasible,
            "constraint_notes": self.constraint_notes,
        }


class DigitalTwin:
    """
    Virtual simulation model of the facility's power network.
    Maintains isolated state that can be stepped, branched, and reset to baseline.
    """

    def __init__(self, config: TwinConfig):
        self.config = config
        self._initial_state = deepcopy(config.initial_state)
        self.state: SystemState = deepcopy(config.initial_state)
        self.last_metrics: Optional[SimulationMetrics] = None

    def reset(self) -> SystemState:
        """Reset digital twin state back to the initial baseline snapshot."""
        self.state = deepcopy(self._initial_state)
        self.last_metrics = None
        return self.state

    def get_state(self) -> SystemState:
        """Return the current state snapshot of the digital twin."""
        return deepcopy(self.state)

    def set_state(self, new_state: SystemState):
        """Update active twin state."""
        self.state = deepcopy(new_state)

    def transition(
        self,
        action: str,
        horizon: timedelta = timedelta(minutes=30),
        predicted_state: Optional[SystemState] = None,
    ) -> Tuple[SystemState, SimulationMetrics]:
        """
        Simulate an action on the digital twin over a given horizon.

        Args:
            action: Action identifier (e.g., 'do_nothing', 'use_battery', 'shift_load', 'hybrid').
            horizon: Duration of the simulation window.
            predicted_state: Optional unmitigated future forecast from Prediction Engine.

        Returns:
            Tuple of (projected_state, simulation_metrics).
        """
        current = self.state
        cfg = self.config

        # Use predicted state if provided to reflect future baseline unmitigated trajectory
        baseline_demand = predicted_state.demand_kw if predicted_state else current.demand_kw
        solar = predicted_state.solar_generation_kw if predicted_state else current.solar_generation_kw
        battery = current.battery_level_pct
        max_discharge = cfg.max_discharge_kw

        action_clean = str(action).lower().replace(" ", "_").replace("-", "_")

        discharged_kw = 0.0
        shifted_kw = 0.0
        projected_demand = baseline_demand
        projected_battery = battery

        duration_hours = max(0.2, horizon.total_seconds() / 3600.0)

        # -------------------------------------------------------------
        # Action Dynamics (Section 5)
        # -------------------------------------------------------------
        if action_clean in ("b", "use_battery", "battery"):
            # Battery behavior: discharge to mitigate deficit between demand and solar
            shortfall = max(0.0, baseline_demand - solar)
            available_battery_kw = (battery / 100.0) * max_discharge * cfg.efficiency
            discharged_kw = min(shortfall, max_discharge, available_battery_kw)
            projected_demand = max(solar, baseline_demand - discharged_kw)

            # Energy drained: (discharged_kw * hours) / capacity
            energy_kwh = discharged_kw * duration_hours / cfg.efficiency
            soc_drain_pct = (energy_kwh / cfg.capacity_kwh) * 100.0
            batt_loss_pct = max(soc_drain_pct, (discharged_kw / max_discharge) * 35.0 * duration_hours)
            projected_battery = max(0.0, battery - batt_loss_pct)
            unit_cost = cfg.cost_per_kwh

        elif action_clean in ("c", "shift_load", "shift_loads", "shift_flexible_loads"):
            # Load-shifting effects: defer flexible loads
            shifted_kw = baseline_demand * 0.14
            projected_demand = max(solar, baseline_demand - shifted_kw)
            projected_battery = battery
            unit_cost = cfg.cost_per_kwh * 1.02

        elif action_clean in ("d", "hybrid", "hybrid_response"):
            # Hybrid: 8% load shift + moderate battery support
            shifted_kw = baseline_demand * 0.08
            interim_demand = baseline_demand - shifted_kw
            shortfall = max(0.0, interim_demand - solar)
            available_battery_kw = (battery / 100.0) * (max_discharge * 0.55) * cfg.efficiency
            discharged_kw = min(shortfall, max_discharge * 0.55, available_battery_kw)
            projected_demand = max(solar, interim_demand - discharged_kw)

            energy_kwh = discharged_kw * duration_hours / cfg.efficiency
            soc_drain_pct = (energy_kwh / cfg.capacity_kwh) * 100.0
            batt_loss_pct = max(soc_drain_pct, (discharged_kw / max_discharge) * 20.0 * duration_hours)
            projected_battery = max(0.0, battery - batt_loss_pct)
            unit_cost = cfg.cost_per_kwh * 0.96

        else:
            # Action A or default: Do nothing
            projected_demand = baseline_demand
            projected_battery = battery
            discharged_kw = 0.0
            shifted_kw = 0.0
            unit_cost = cfg.cost_per_kwh * 1.10

        # Calculate projected metrics
        cost = projected_demand * unit_cost
        effective_demand = max(0.1, projected_demand)
        renewable_util = min(100.0, max(0.0, (solar / effective_demand) * 100.0))

        # Degradation impact
        dod_delta = max(0.0, battery - projected_battery)
        degradation_impact_pct = round((dod_delta / 100.0) * (1.0 / cfg.battery_cycle_life) * 100.0, 4)

        # Constraint boundary validation
        is_feasible = True
        violation_reasons = []
        if projected_battery < cfg.min_battery_reserve_pct:
            is_feasible = False
            violation_reasons.append(
                f"Battery reserve {projected_battery:.1f}% below minimum {cfg.min_battery_reserve_pct:.1f}%"
            )
        if projected_demand > cfg.max_allowable_peak_kw:
            is_feasible = False
            violation_reasons.append(
                f"Peak demand {projected_demand:.1f} kW exceeds limit {cfg.max_allowable_peak_kw:.1f} kW"
            )

        constraint_notes = "; ".join(violation_reasons) if violation_reasons else "All constraints satisfied"

        metrics = SimulationMetrics(
            peak_demand_kw=round(projected_demand, 2),
            cost=round(cost, 2),
            battery_reserve_pct=round(projected_battery, 2),
            renewable_utilization_pct=round(renewable_util, 2),
            discharged_kw=round(discharged_kw, 2),
            shifted_kw=round(shifted_kw, 2),
            degradation_impact_pct=degradation_impact_pct,
            is_feasible=is_feasible,
            constraint_notes=constraint_notes,
        )
        self.last_metrics = metrics

        projected_ts = (
            current.timestamp + horizon
            if isinstance(current.timestamp, datetime)
            else datetime.now(timezone.utc)
        )

        next_state = SystemState(
            timestamp=projected_ts,
            demand_kw=round(projected_demand, 2),
            solar_generation_kw=round(solar, 2),
            battery_level_pct=round(projected_battery, 2),
            temperature_c=current.temperature_c,
            occupancy=current.occupancy,
        )
        self.state = next_state
        return next_state, metrics

    def simulate_what_if(
        self,
        action: str,
        horizon: timedelta = timedelta(minutes=30),
        predicted_state: Optional[SystemState] = None,
    ) -> Tuple[SystemState, SimulationMetrics]:
        """
        Pure hypothetical query without side-effects (Section 3).
        Leaves the twin's active state unmutated.
        """
        saved_state = deepcopy(self.state)
        saved_metrics = deepcopy(self.last_metrics)
        try:
            return self.transition(action, horizon=horizon, predicted_state=predicted_state)
        finally:
            self.state = saved_state
            self.last_metrics = saved_metrics

    def execute_action(
        self,
        action: str,
        mode: str = "virtual",
        horizon: timedelta = timedelta(minutes=30),
    ) -> Tuple[SystemState, SimulationMetrics]:
        """
        Execution interface (Section 6).
        Shares common action interface with physical controllers.
        """
        return self.transition(action, horizon=horizon)

    @staticmethod
    def calculate_improvement(
        before_state: SystemState,
        after_state: SystemState,
    ) -> Dict[str, float]:
        """
        Calculates before vs after improvement for the Measure stage (Section 7).
        """
        b_peak = before_state.demand_kw
        a_peak = after_state.demand_kw
        diff_kw = round(b_peak - a_peak, 2)
        pct = round((diff_kw / b_peak * 100.0), 2) if b_peak > 0 else 0.0
        batt_delta = round(after_state.battery_level_pct - before_state.battery_level_pct, 2)

        return {
            "before_peak_kw": b_peak,
            "after_peak_kw": a_peak,
            "peak_reduction_kw": diff_kw,
            "improvement_pct": pct,
            "battery_delta_pct": batt_delta,
        }


@dataclass
class SimulationRunRecord:
    """Audit record for an individual simulation branch execution (Section 8 Principle 5)."""
    run_id: str
    branch_id: str
    candidate_id: str
    timestamp: str
    decision_horizon_minutes: int
    baseline_state_snapshot: Dict[str, Any]
    predicted_state_snapshot: Optional[Dict[str, Any]]
    action_applied: str
    projected_state: Dict[str, Any]
    metrics: Dict[str, Any]
    latency_ms: float


@dataclass
class SimulatedOutcome:
    """Standardized simulation outcome per candidate (Section 4.2)."""
    candidate_id: str
    projected_state: Dict[str, Any]
    metrics: Dict[str, Any]
    branch_id: Optional[str] = None
    action_label: Optional[str] = None


@dataclass
class SimulationPackage:
    """Packaged results of all candidate branches ready for Optimization Engine handoff (Section 5.5)."""
    outcomes: List[SimulatedOutcome]
    decision_horizon_minutes: int
    baseline_state: Dict[str, Any]
    audit_records: List[SimulationRunRecord] = field(default_factory=list)
    total_execution_ms: float = 0.0


class SimulationEngine:
    """
    Simulation Engine (Process/Orchestration Layer).
    Executes what-if branching scenarios against the Digital Twin and prepares
    standardized comparable projections for the Optimization Engine.
    """

    def __init__(
        self,
        config: Optional[TwinConfig] = None,
        max_workers: int = 4,
    ):
        self.default_config = config
        self.max_workers = max_workers
        self._audit_log: List[SimulationRunRecord] = []

    def get_audit_log(self) -> List[SimulationRunRecord]:
        return list(self._audit_log)

    def clear_audit_log(self):
        self._audit_log.clear()

    def run(
        self,
        twin: DigitalTwin,
        action: str,
        horizon: timedelta = timedelta(minutes=30),
        predicted_state: Optional[SystemState] = None,
    ) -> SystemState:
        """Run simulation on an existing twin instance."""
        sim_state, _ = twin.transition(action, horizon=horizon, predicted_state=predicted_state)
        return sim_state

    def simulate_candidates(
        self,
        initial_state: SystemState,
        candidates: List[str],
        horizon: timedelta = timedelta(minutes=30),
        predicted_state: Optional[SystemState] = None,
    ) -> List[Tuple[str, SystemState, SimulationMetrics]]:
        """
        Legacy tuple-based interface: simulate all candidate actions in parallel branching fashion.
        """
        twin = DigitalTwin(self.default_config or TwinConfig(initial_state=initial_state))
        results = []
        for cand in candidates:
            twin.reset()
            sim_state, metrics = twin.transition(cand, horizon=horizon, predicted_state=predicted_state)
            results.append((cand, sim_state, metrics))
        return results

    def _execute_branch(
        self,
        branch_id: str,
        cand_id: str,
        baseline_state: SystemState,
        predicted_state: Optional[SystemState],
        horizon_minutes: int,
    ) -> Tuple[SimulatedOutcome, SimulationRunRecord]:
        import time
        import uuid
        t0 = time.perf_counter()
        now_ts = datetime.now(timezone.utc).isoformat()

        twin_cfg = self.default_config or TwinConfig(initial_state=baseline_state)
        twin_cfg_branch = deepcopy(twin_cfg)
        twin_cfg_branch.initial_state = deepcopy(baseline_state)
        twin = DigitalTwin(twin_cfg_branch)

        horizon = timedelta(minutes=horizon_minutes)
        sim_state, raw_metrics = twin.transition(
            action=cand_id,
            horizon=horizon,
            predicted_state=predicted_state,
        )

        peak_demand = raw_metrics.peak_demand_kw
        solar = sim_state.solar_generation_kw
        discharged = raw_metrics.discharged_kw
        batt_reserve = raw_metrics.battery_reserve_pct

        energy_waste = round(max(0.0, (solar + discharged) - peak_demand), 2) if peak_demand > 0 else 0.0
        risk_penalty = round(max(0.0, peak_demand - solar), 2) if solar > 0 else peak_demand
        reliability_margin = round(max(0.0, batt_reserve - 20.0), 2)
        battery_health = round(max(0.0, batt_reserve - (raw_metrics.degradation_impact_pct * 100.0)), 2)

        standardized_metrics = {
            "peak_demand_kw": peak_demand,
            "cost": raw_metrics.cost,
            "battery_reserve_pct": batt_reserve,
            "renewable_utilization_pct": raw_metrics.renewable_utilization_pct,
            "discharged_kw": discharged,
            "shifted_kw": raw_metrics.shifted_kw,
            "degradation_impact_pct": raw_metrics.degradation_impact_pct,
            "energy_waste": energy_waste,
            "risk": risk_penalty,
            "reliability": reliability_margin,
            "battery_health": battery_health,
            "is_feasible": raw_metrics.is_feasible,
            "constraint_notes": raw_metrics.constraint_notes,
        }

        latency_ms = round((time.perf_counter() - t0) * 1000.0, 2)

        outcome = SimulatedOutcome(
            candidate_id=cand_id,
            projected_state={
                "timestamp": sim_state.timestamp.isoformat() if hasattr(sim_state.timestamp, "isoformat") else str(sim_state.timestamp),
                "demand_kw": sim_state.demand_kw,
                "solar_generation_kw": sim_state.solar_generation_kw,
                "battery_level_pct": sim_state.battery_level_pct,
                "temperature_c": sim_state.temperature_c,
                "occupancy": sim_state.occupancy,
            },
            metrics=standardized_metrics,
            branch_id=branch_id,
        )

        audit_rec = SimulationRunRecord(
            run_id=f"run_{uuid.uuid4().hex[:8]}",
            branch_id=branch_id,
            candidate_id=cand_id,
            timestamp=now_ts,
            decision_horizon_minutes=horizon_minutes,
            baseline_state_snapshot={
                "demand_kw": baseline_state.demand_kw,
                "solar_generation_kw": baseline_state.solar_generation_kw,
                "battery_level_pct": baseline_state.battery_level_pct,
            },
            predicted_state_snapshot={
                "demand_kw": predicted_state.demand_kw,
                "solar_generation_kw": predicted_state.solar_generation_kw,
            } if predicted_state else None,
            action_applied=cand_id,
            projected_state=outcome.projected_state,
            metrics=standardized_metrics,
            latency_ms=latency_ms,
        )

        return outcome, audit_rec

    def simulate_package(
        self,
        baseline_state: SystemState,
        candidates: List[Union[str, Any]],
        predicted_state: Optional[SystemState] = None,
        horizon_minutes: int = 30,
        parallel: bool = False,
    ) -> SimulationPackage:
        """Executes the full 5-step simulation process (Section 5) with audit records."""
        import time
        from concurrent.futures import ThreadPoolExecutor
        t_start = time.perf_counter()

        extracted_cands = []
        for idx, cand in enumerate(candidates):
            cid = cand.get("id") if isinstance(cand, dict) else getattr(cand, "id", str(cand))
            extracted_cands.append((idx, cid))

        outcomes: List[SimulatedOutcome] = []
        audit_records: List[SimulationRunRecord] = []

        if parallel and len(extracted_cands) > 1:
            with ThreadPoolExecutor(max_workers=min(len(extracted_cands), self.max_workers)) as executor:
                futures = [
                    executor.submit(
                        self._execute_branch,
                        f"branch_{idx}_{cid}",
                        cid,
                        baseline_state,
                        predicted_state,
                        horizon_minutes,
                    )
                    for idx, cid in extracted_cands
                ]
                for future in futures:
                    outcome, audit_rec = future.result()
                    outcomes.append(outcome)
                    audit_records.append(audit_rec)
        else:
            for idx, cid in extracted_cands:
                outcome, audit_rec = self._execute_branch(
                    branch_id=f"branch_{idx}_{cid}",
                    cand_id=cid,
                    baseline_state=baseline_state,
                    predicted_state=predicted_state,
                    horizon_minutes=horizon_minutes,
                )
                outcomes.append(outcome)
                audit_records.append(audit_rec)

        total_ms = round((time.perf_counter() - t_start) * 1000.0, 2)
        self._audit_log.extend(audit_records)

        return SimulationPackage(
            outcomes=outcomes,
            decision_horizon_minutes=horizon_minutes,
            baseline_state={
                "demand_kw": baseline_state.demand_kw,
                "solar_generation_kw": baseline_state.solar_generation_kw,
                "battery_level_pct": baseline_state.battery_level_pct,
            },
            audit_records=audit_records,
            total_execution_ms=total_ms,
        )
