"""
VOLTERRA — Digital Twin Component
=================================
Implements the VOLTERRA Digital Twin Design Document (Version 1.0, September 2026).

Answers the central simulation question:
    "If I choose this action, what happens?"

Role:
- Sits at the SIMULATE stage of the closed-loop pipeline.
- Simulates candidate actions without real-world side effects.
- Models battery dynamics (charge/discharge rates, SOC limits, degradation impact).
- Models load-shifting effects (peak clipping, deferrable load rescheduling).
- Models renewable supply dynamics over the simulation horizon.
- Validates constraint boundaries (minimum battery reserve, max peak demand).
- Provides interface parity for both virtual and physical execution modes.
"""

from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Optional, Dict, Any, Tuple, Union, List

from engine.observe import SystemState, normalize_system_state


@dataclass
class TwinConfig:
    """
    Physical assets and operational boundaries of the Digital Twin.
    """
    initial_state: SystemState
    max_discharge_kw: float = 5.0
    max_charge_kw: float = 5.0
    efficiency: float = 0.95
    capacity_kwh: float = 13.5
    cost_per_kwh: float = 0.50
    # Constraint boundaries (Section 5)
    min_battery_reserve_pct: float = 20.0
    max_allowable_peak_kw: float = 15.0
    # Degradation modeling parameters
    battery_cycle_life: int = 4000  # cycles at 80% DoD
    cell_nominal_voltage: float = 48.0


@dataclass
class SimulationMetrics:
    """
    Key simulated metrics generated by the Digital Twin (Section 4.2).
    """
    peak_demand_kw: float
    cost: float
    battery_reserve_pct: float
    renewable_utilization_pct: float
    discharged_kw: float = 0.0
    shifted_kw: float = 0.0
    # Battery degradation impact of use (Section 5)
    degradation_impact_pct: float = 0.0
    # Constraint compliance check (Section 5)
    is_feasible: bool = True
    constraint_notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "peak_demand_kw": self.peak_demand_kw,
            "cost": self.cost,
            "battery_reserve_pct": self.battery_reserve_pct,
            "renewable_utilization_pct": self.renewable_utilization_pct,
            "discharged_kw": self.discharged_kw,
            "shifted_kw": self.shifted_kw,
            "degradation_impact_pct": self.degradation_impact_pct,
            "is_feasible": self.is_feasible,
            "constraint_notes": self.constraint_notes,
        }


class DigitalTwin:
    """
    Virtual simulation model of the facility's power network.

    Features:
    1. Simulation before action — tests candidate actions without affecting physical assets.
    2. Parallel branching — maintains isolated state snapshots for branching exploration.
    3. Representative physical fidelity — models battery SOC, load-shift curves, and solar dynamics.
    4. Interface parity — shares common action interface between virtual and physical execution.
    5. Measurement baseline — feeds simulated outcomes into the post-action Measure stage.
    """

    def __init__(self, config: TwinConfig):
        self.config = config
        self._initial_state = deepcopy(config.initial_state)
        self.state: SystemState = deepcopy(config.initial_state)
        self.last_metrics: Optional[SimulationMetrics] = None

    def reset(self) -> SystemState:
        """Reset digital twin state back to pristine initial baseline snapshot."""
        self.state = deepcopy(self._initial_state)
        self.last_metrics = None
        return self.state

    def get_state(self) -> SystemState:
        """Return a read-only snapshot of current twin state."""
        return deepcopy(self.state)

    def set_state(self, new_state: SystemState):
        """Update the twin's active state."""
        self.state = deepcopy(new_state)

    def transition(
        self,
        action_id: str,
        horizon: timedelta = timedelta(minutes=30),
        predicted_state: Optional[SystemState] = None,
    ) -> tuple[SystemState, SimulationMetrics]:
        """
        Calculates the state transition resulting from a candidate action over horizon.

        Inputs (Section 4.1):
        - Current SystemState (self.state)
        - Predicted SystemState (optional unmitigated future trajectory)
        - Candidate Action (action_id)

        Outputs (Section 4.2):
        - Projected Future State
        - Key Simulated Metrics
        """
        cfg = self.config
        current = self.state

        # Use predicted state if provided to reflect future baseline unmitigated trajectory
        baseline_demand = predicted_state.demand_kw if predicted_state else current.demand_kw
        solar = predicted_state.solar_generation_kw if predicted_state else current.solar_generation_kw
        battery = current.battery_level_pct
        max_discharge = cfg.max_discharge_kw

        key = str(action_id).lower().replace(" ", "_").replace("-", "_")

        discharged_kw = 0.0
        shifted_kw = 0.0
        projected_demand = baseline_demand
        projected_battery = battery

        duration_hours = max(0.2, horizon.total_seconds() / 3600.0)

        # -------------------------------------------------------------
        # 1. Action Dynamics (Section 5)
        # -------------------------------------------------------------
        if key in ("b", "use_battery", "battery"):
            # Battery behavior: discharge to mitigate deficit between demand and solar
            shortfall = max(0.0, baseline_demand - solar)
            # Available discharge limited by current SOC and rate
            available_battery_kw = (battery / 100.0) * max_discharge * cfg.efficiency
            discharged_kw = min(shortfall, max_discharge, available_battery_kw)
            projected_demand = max(solar, baseline_demand - discharged_kw)

            # Energy drained: (discharged_kw * hours) / capacity
            energy_kwh = discharged_kw * duration_hours / cfg.efficiency
            soc_drain_pct = (energy_kwh / cfg.capacity_kwh) * 100.0
            # Ensure representative residential/commercial battery dynamics
            batt_loss_pct = max(soc_drain_pct, (discharged_kw / max_discharge) * 35.0 * duration_hours)
            projected_battery = max(0.0, battery - batt_loss_pct)
            unit_cost = cfg.cost_per_kwh

        elif key in ("c", "shift_load", "shift_loads", "shift_flexible_loads"):
            # Load-shifting effects: defer flexible loads (HVAC, thermal, charging)
            shifted_kw = baseline_demand * 0.14
            projected_demand = max(solar, baseline_demand - shifted_kw)
            projected_battery = battery
            # Slight administrative/scheduling cost
            unit_cost = cfg.cost_per_kwh * 1.02

        elif key in ("d", "hybrid", "hybrid_response"):
            # Hybrid: 8% load shift + moderate battery discharge
            shifted_kw = baseline_demand * 0.08
            interim_demand = baseline_demand - shifted_kw
            shortfall = max(0.0, interim_demand - solar)
            available_battery_kw = (battery / 100.0) * (max_discharge * 0.55) * cfg.efficiency
            discharged_kw = min(shortfall, max_discharge * 0.55, available_battery_kw)
            projected_demand = max(solar, interim_demand - discharged_kw)

            energy_kwh = discharged_kw * duration_hours / cfg.efficiency
            soc_drain_pct = (energy_kwh / cfg.capacity_kwh) * 100.0
            batt_loss_pct = max(soc_drain_pct, (discharged_kw / max_discharge) * 20.0 * duration_hours)
            projected_battery = max(0.0, battery - batt_loss_pct)
            unit_cost = cfg.cost_per_kwh * 0.96

        else:
            # Action A or default: Do nothing
            projected_demand = baseline_demand
            projected_battery = battery
            discharged_kw = 0.0
            shifted_kw = 0.0
            unit_cost = cfg.cost_per_kwh * 1.10  # higher peak tariff

        # -------------------------------------------------------------
        # 2. Key Simulated Metrics (Section 4.2 & 5)
        # -------------------------------------------------------------
        cost = projected_demand * unit_cost
        effective_demand = max(0.1, projected_demand)
        renewable_util = min(100.0, max(0.0, (solar / effective_demand) * 100.0))

        # Battery degradation impact of use:
        # proportional to depth of discharge (DoD) delta and high C-rate throughput
        dod_delta = max(0.0, battery - projected_battery)
        degradation_impact_pct = round((dod_delta / 100.0) * (1.0 / cfg.battery_cycle_life) * 100.0, 4)

        # Constraint boundaries check (Section 5):
        # - minimum required battery reserve
        # - maximum allowable peak demand
        is_feasible = True
        violation_reasons = []
        if projected_battery < cfg.min_battery_reserve_pct:
            is_feasible = False
            violation_reasons.append(
                f"Battery reserve {projected_battery:.1f}% below minimum {cfg.min_battery_reserve_pct:.1f}%"
            )
        if projected_demand > cfg.max_allowable_peak_kw:
            is_feasible = False
            violation_reasons.append(
                f"Peak demand {projected_demand:.1f} kW exceeds maximum limit {cfg.max_allowable_peak_kw:.1f} kW"
            )

        constraint_notes = "; ".join(violation_reasons) if violation_reasons else "All constraints satisfied"

        metrics = SimulationMetrics(
            peak_demand_kw=round(projected_demand, 2),
            cost=round(cost, 2),
            battery_reserve_pct=round(projected_battery, 2),
            renewable_utilization_pct=round(renewable_util, 2),
            discharged_kw=round(discharged_kw, 2),
            shifted_kw=round(shifted_kw, 2),
            degradation_impact_pct=degradation_impact_pct,
            is_feasible=is_feasible,
            constraint_notes=constraint_notes,
        )
        self.last_metrics = metrics

        # Projected Future State (Section 4.2)
        projected_ts = (
            current.timestamp + horizon
            if isinstance(current.timestamp, datetime)
            else datetime.now(timezone.utc)
        )

        next_state = SystemState(
            timestamp=projected_ts,
            demand_kw=round(projected_demand, 2),
            solar_generation_kw=round(solar, 2),
            battery_level_pct=round(projected_battery, 2),
            temperature_c=current.temperature_c,
            occupancy=current.occupancy,
        )
        self.state = next_state
        return next_state, metrics

    def simulate_what_if(
        self,
        action_id: str,
        horizon: timedelta = timedelta(minutes=30),
        predicted_state: Optional[SystemState] = None,
    ) -> tuple[SystemState, SimulationMetrics]:
        """
        Pure hypothetical query (Section 3): "If I choose this action, what happens?"
        Leaves the digital twin's current state completely unchanged (side-effect free).
        """
        saved_state = deepcopy(self.state)
        saved_metrics = deepcopy(self.last_metrics)
        try:
            return self.transition(action_id, horizon=horizon, predicted_state=predicted_state)
        finally:
            self.state = saved_state
            self.last_metrics = saved_metrics

    def execute_action(
        self,
        action_id: str,
        mode: str = "virtual",
        horizon: timedelta = timedelta(minutes=30),
    ) -> tuple[SystemState, SimulationMetrics]:
        """
        Applies action to the digital twin (Section 6).
        In virtual mode: transitions the active twin state to the new operational state.
        In physical mode: serves as pre-validation before physical device dispatch.
        """
        return self.transition(action_id, horizon=horizon)

    @staticmethod
    def calculate_improvement(
        before_state: SystemState,
        after_state: SystemState,
    ) -> Dict[str, float]:
        """
        Quantifies improvement for the Measure stage (Section 7):
            Before: Peak = 9.4 kW
            After:  Peak = 7.9 kW
            -> Improvement calculated
        """
        b_peak = before_state.demand_kw
        a_peak = after_state.demand_kw
        diff_kw = round(b_peak - a_peak, 2)
        pct = round((diff_kw / b_peak * 100.0), 2) if b_peak > 0 else 0.0
        batt_delta = round(after_state.battery_level_pct - before_state.battery_level_pct, 2)

        return {
            "before_peak_kw": b_peak,
            "after_peak_kw": a_peak,
            "peak_reduction_kw": diff_kw,
            "improvement_pct": pct,
            "battery_delta_pct": batt_delta,
        }
